name: Go
on: [push,release]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build
        run: go build -v .

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        if: ${{ github.event_name == 'release' }}
        with:
          name: artifacts-${{ matrix.os }}
          if-no-files-found: ignore
          path: |
            legion
            legion.exe
  release:
    runs-on: ubuntu-22.04
    needs: build
    if: ${{ github.event_name == 'release' }}
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./**