name: Go
on: [push,release]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build
        run: go build -v .

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        if: ${{ github.event_name == 'release' }}
        with:
          name: artifacts-${{ matrix.os }}
          if-no-files-found: ignore
          path: |
            legion
            legion.exe
      
      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        if: ${{ github.event_name == 'release' }}
        with:
          files: artifacts-*